---
title: "proposal_presentation"
author: "Angel Sarmiento"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```


```{r}
library(here)
library(ggplot2)
library(dplyr)
library(readr)
library(purrr)
library(stringr)
library(DT)
library(tidyr)
```

```{r, warning = FALSE, message=FALSE}
data <- read_csv(here("data/courses-list-fpu.csv"))
```


```{r Making the column names stable}
colnames(data) <- str_replace_all(colnames(data), " |\\/", "_")
colnames(data) <- str_replace_all(colnames(data), "\\:|\\?|\\_\\(Rendered_no_HTML\\)|\\(s\\)", "")

colnames(data)
```

```{r}
test <- data %>%
   mutate(degree_usage = strsplit(as.character(Degree_Program_Usage), "Bachelor of Science,"),
          degree_track = strsplit(as.character(Degree_Program_Usage), "Track, "))


 test2 <- data %>% tidyr::separate_rows(Degree_Program_Usage, sep = "\\(Program Description\\),") 


 test2 %>% tidyr::separate_rows(Degree_Program_Usage, sep = "\\(")

 test2$Degree_Program_Usage <- test2$Degree_Program_Usage %>% str_replace_all( "Bachelor of Science,|Master of Science,", "")
```


```{r Working with Degree Programs}
ftrd_prog <- data %>% mutate(deg = strsplit(as.character(Degree_Program_Usage), ", |,")) 

ftrd_prog <- ftrd_prog %>% 
  mutate(deg_prog = map(deg, as_tibble)) %>% 
  unnest(cols = c(deg_prog)) %>% 
  rename(deg_prog = value)

ftrd_prog%>%
  filter(!deg_prog == "Bachelor of Science") %>% filter(!deg_prog == "Master of Science") %>% 
  filter(!deg_prog %in% c("Engine", "E", "Cybe", "Bachel", "Bache", 
                        "B", "Applied Ma", "Appli", "Additional Florida Requirements", "Environm")) %>% 
  #  filter(!is.na(Degree_Program_Usage)) %>% filter(!grepl(Degree_Program_Usage, pattern = "Additional")) %>% 
  # filter(!grepl(Degree_Program_Usage, pattern = "Track -")) %>%
  # filter(!grepl(Degree_Program_Usage, pattern = "\\(Plan of Study\\)")) %>% 
  #  filter(!is.na(Degree_Program_Usage)) %>%
   ggplot(aes(x = deg_prog)) +
   geom_histogram(stat = "count") +
  coord_flip()
```


```{r Separating course outlines}
# This will eventually be its own script
test <- data %>% 
  mutate(outlines = strsplit(as.character(Course_Outline), "[\\\r\\\n\\\t]+")) %>% 
  select(outlines)

```



```{r}
data <- data %>% 
  mutate(Department_Name = ifelse(is.na(Department_Name),"Other", Department_Name))
```


```{r}
data %>% group_by(Department_Name) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x = reorder(Department_Name, count), y = count,
             fill=factor(ifelse(Department_Name=="Data Science and Business Analytics","Highlighted","Normal")))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(name = "area", values=c("#532d8e","#B1B3B5")) +
  labs(x = "Department Name", y = "", title = "Number of Courses by Department")+
  theme_minimal()+
  theme(legend.position = 'none') +
  coord_flip() 
  
```

```{r}

# data %>% select(c(Department_Name, Name, Course_Type, Course_Objectives)) %>% 
#   DT::datatable(options = list( dom = 'Bfrtip',
#     buttons = c('copy')))

```


```{r}

```



