---
title: "Preliminary Text Data Cleaning/Analysis: `r params$department`"
author: "Angel Sarmiento"
date: "10/5/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
params:
  department: 
    label: "Department"
    value: "Data Science and Business Analytics"
    choices: 
    - "Data Science and Business Analytics"
    - "Mechanical Engineering and Environmental Engineering"
    - "Computer Science"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```



```{r Library Import}
library(here)
library(ggplot2)
library(dplyr)
library(readr)
library(purrr)
library(stringr)
library(DT)
library(tidyr)
library(tidytext)
library(tm)
library(FactoMineR)
library(factoextra)
library(plotly)
```

```{r Scripts and data, warning = FALSE, message=FALSE}
source(here("scripts/functions/transform_course_data.R"))
data <- read_csv(here("data/courses-list-fpu.csv"))

if(!dir.exists(here("img/"))) {
  dir.create(here("img/"))
}
```



```{r Running the function to get the transformed data}
full_outl <- data %>% 
  clean_columns() %>% 
  transform_course_data(data) %>% 
  filter(Department_Name == params$department) %>% 
  filter(Is_Active == 1) %>% 
  filter(Course_ID != "FIN_2000")
```

# MCA with Bigrams {.tabset} 

```{r Creating the document-term matrix, bigram}
terms_bigram <- full_outl %>% 
  select(Course_ID, new_col) %>% 
  unnest_tokens("outline_word", new_col, token = "ngrams", n = 2) %>% 
  separate(outline_word, c("word1", "word2")) %>% 
  filter(!word1 %in% stop_words$word) %>%
  filter(!grepl("^[0-9]", word1)) %>% 
  filter(!word2 %in% stop_words$word) %>% 
  filter(!grepl("^[0-9]", word2)) %>% 
  unite(outline_bigram, word1, word2, sep = " ") %>% 
  filter(!outline_bigram == "NA NA")

bigram_dtm <- terms_bigram %>% 
  count(Course_ID, outline_bigram, sort = TRUE) %>% 
  cast_dtm(Course_ID, outline_bigram, n)
```

```{r MCA Checking eigenvalues}
bigram_matrix <- as.matrix(bigram_dtm)

bigram_ca <- FactoMineR::CA(bigram_matrix, graph = F)
# Check eigenvalues
# bigram_ca$eig
```




## Dimensions 1 and 2

```{r MCA Bigram DTM}
options(ggrepel.max.overlaps = Inf)
factoextra::fviz_ca_biplot(bigram_ca, 
                           geom.row = c("text"),
                           geom.col = c("point", "text"),
                           row.var = "#532d8e",
                           col.row = "#54565a",
                           col.col = "#532d8e",
                           arrow = c("FALSE", "FALSE"),
                           labelsize = 2,
                           select.col = list(contrib = 100),
                           select.row = list(contrib = 30),
                           alpha.row = 0.3,
                           repel = T,
                           title = "DSBA Curriculum - Biplot")

ggsave(paste0("final-doc/Content/images/", 
              ifelse(
                params$department == "Computer Science",
                "mca_bp_cs_1.png",
                "mca_bp_1.png"
              )))


ggsave('img/mca_bp_1.png', dpi = 300)

```


## Dimensions 3 and 4

```{r}
factoextra::fviz_ca_biplot(bigram_ca, 
                           geom.row = c("point","text"),
                           geom.col = c("point", "text"),
                           row.var = "#532d8e",
                           col.row = "#54565a",
                           col.col = "#532d8e",
                           labelsize = 2,
                           select.col = list(cos2 = .10),
                           # select.row = list(cos2 = .12),
                           alpha.row = 0.3, repel = T,
                           axes = c(3, 4),
                           title = "DSBA Curriculum - Biplot")

ggsave(paste0("final-doc/Content/images/", 
              ifelse(
                params$department == "Computer Science",
                "mca_bp_cs_2.png",
                "mca_bp_2.png"
              )))


ggsave('img/mca_bp_2.png', dpi = 300)
```

```{r}
factoextra::fviz_eig(bigram_ca, addlabels = TRUE, ylim = c(0, 100))
```



# MCA with Reduced Bigrams Matrix {.tabset}

## Reduced Matrix: Dims 1 and 2

```{r}
my_row_sums <- rowSums(bigram_matrix) %>% as.numeric()
rows_to_remove <- which(my_row_sums < median(my_row_sums))

mini_df <- bigram_matrix[-rows_to_remove, ]
```

```{r}
mini_ca <- FactoMineR::CA(mini_df,
                          graph = F)

factoextra::fviz_ca_biplot(mini_ca, 
                           geom.row = c("point","text"),
                           geom.col = c("point", "text"),
                           row.var = "#532d8e",
                           col.row = "#54565a",
                           col.col = "#532d8e",
                           labelsize = 2,
                           select.col = list(contrib = 80),
                           select.row = list(contrib = 30),
                           alpha.row = 0.3, repel = T,
                           axes = c(1, 2),
                           title = "DSBA Curriculum - Biplot")


ggsave(paste0("final-doc/Content/images/", 
              ifelse(
                params$department == "Computer Science",
                "mca_bp_cs_3.png",
                "mca_bp_3.png"
              )))

ggsave('img/mca_bp_3.png', dpi = 300)

```



## Reduced Matrix: Dims 3 and 4

```{r}
factoextra::fviz_ca_biplot(mini_ca, 
                           geom.row = c("point","text"),
                           geom.col = c("point", "text"),
                           row.var = "#532d8e",
                           col.row = "#54565a",
                           col.col = "#532d8e",
                           labelsize = 2,
                           select.col = list(contrib = 80),
                           select.row = list(contrib = 30),
                           alpha.row = 0.3, repel = T,
                           axes = c(3, 4),
                           title = "DSBA Curriculum - Biplot")

ggsave(paste0("final-doc/Content/images/", 
              ifelse(
                params$department == "Computer Science",
                "mca_bp_cs_4.png",
                "mca_bp_4.png"
              )))

ggsave('img/mca_bp_4.png', dpi = 300)

```





# Misc Analyses

```{r}
# test <- data %>%
#    mutate(degree_usage = strsplit(as.character(Degree_Program_Usage), "Bachelor of Science,"),
#           degree_track = strsplit(as.character(Degree_Program_Usage), "Track, "))
# 
# 
#  test2 <- data %>% tidyr::separate_rows(Degree_Program_Usage, sep = "\\(Program Description\\),") 
# 
# 
#  test2 %>% tidyr::separate_rows(Degree_Program_Usage, sep = "\\(")
# 
#  test2$Degree_Program_Usage <- test2$Degree_Program_Usage %>% str_replace_all( "Bachelor of Science,|Master of Science,", "")
```


```{r Working with Degree Programs}
# ftrd_prog_in <- full_outl %>% mutate(deg = strsplit(as.character(Degree_Program_Usage), ", |,")) 
# 
# ftrd_prog <- ftrd_prog_in %>% 
#   mutate(deg_prog = map(deg, as_tibble)) %>% 
#   unnest(cols = c(deg_prog)) %>% 
#   rename(deg_prog = value)
```


```{r Working with Degree Programs 2}
# ftrd_prog %>%
#   filter(!deg_prog == "Bachelor of Science") %>% filter(!deg_prog == "Master of Science") %>% 
#   filter(!deg_prog %in% c("Engine", "E", "Cybe", "Bachel", "Bache", 
#                         "B", "Applied Ma", "Appli", "Additional Florida Requirements", "Environm")) %>% 
#   group_by(deg_prog) %>% 
#   summarise(count = n()) %>%
#   arrange(desc(count)) %>% 
#   slice(1:22) %>% 
#   #  filter(!is.na(Degree_Program_Usage)) %>% filter(!grepl(Degree_Program_Usage, pattern = "Additional")) %>% 
#   # filter(!grepl(Degree_Program_Usage, pattern = "Track -")) %>%
#   # filter(!grepl(Degree_Program_Usage, pattern = "\\(Plan of Study\\)")) %>% 
#   #  filter(!is.na(Degree_Program_Usage)) %>%
#    ggplot(aes(x = reorder(deg_prog, count), y = count)) +
#    geom_bar(stat = "identity") +
#   coord_flip()
```


```{r}
# data_pg <- full_outl %>% 
#   mutate(Department_Name = ifelse(is.na(Department_Name),"Other", Department_Name))
# 
# data_pg %>% group_by(Department_Name) %>% 
#   summarise(count = n()) %>% 
#   ggplot(aes(x = reorder(Department_Name, count), y = count,
#              fill=factor(ifelse(Department_Name=="Data Science and Business Analytics","Highlighted","Normal")))) +
#   geom_bar(stat = "identity") +
#   scale_fill_manual(name = "area", values=c("#532d8e","#B1B3B5")) +
#   labs(x = "Department Name", y = "", title = "Number of Courses by Department")+
#   theme_minimal()+
#   theme(legend.position = 'none') +
#   coord_flip() 
#   
```






